# Generated by Django 4.2.5 on 2025-05-23 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('permiso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permiso_extra', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Permiso Extra',
                'verbose_name_plural': 'Permisos Extras',
            },
        ),
    ]
